# Data Analysis with Pandas - Video Game Sales

## Peng Chen,    May 27 2020

In [3]:
import pandas as pd

In [15]:
df = pd.read_csv('./vgsales.csv')

## 1. Which company is the most common video game publisher?

In [11]:
most_common_publisher=df["Publisher"].mode().values[0]
most_common_publisher

'Electronic Arts'

## 2. What’s the most common platform?

In [17]:
most_common_platform = df["Platform"].mode().values[0]
most_common_platform

'DS'

## 3. What about the most common genre?

In [18]:
most_common_genre = df["Genre"].mode().values[0]
most_common_genre

'Action'

## 4. What are the top 20 highest grossing games?

In [20]:
top_twenty_highest_grossing_games = df[["Name","Global_Sales"]].sort_values('Global_Sales', ascending=False)[:20]
top_twenty_highest_grossing_games

                                            Name  Global_Sales
0                                     Wii Sports         82.74
1                              Super Mario Bros.         40.24
2                                 Mario Kart Wii         35.82
3                              Wii Sports Resort         33.00
4                       Pokemon Red/Pokemon Blue         31.37
5                                         Tetris         30.26
6                          New Super Mario Bros.         30.01
7                                       Wii Play         29.02
8                      New Super Mario Bros. Wii         28.62
9                                      Duck Hunt         28.31
10                                    Nintendogs         24.76
11                                 Mario Kart DS         23.42
12                   Pokemon Gold/Pokemon Silver         23.10
13                                       Wii Fit         22.72
14                                  Wii Fit Plus         22.00
15                            Kinect Adventures!         21.82
16                            Grand Theft Auto V         21.40
17                 Grand Theft Auto: San Andreas         20.81
18                             Super Mario World         20.61
19  Brain Age: Train Your Brain in Minutes a Day         20.22

## 5. For North American video game sales, what’s the median?

In [39]:
NA_median = df["NA_Sales"].median()
NA_median

0.08

    - Provide a secondary output showing ten games surrounding the median sales output
        - assume that games with same median value are sorted in descending order

In [56]:
df[df.NA_Sales==NA_median].sort_values("Name", ascending = False)[:10]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
7835,7837,uDraw Studio: Instant Artist,Wii,2011.0,Misc,THQ,0.08,0.09,0.00,0.02,0.19
7088,7090,pro evolution soccer 2011,Wii,2010.0,Sports,Konami Digital Entertainment,0.08,0.10,0.03,0.02,0.23
10625,10627,nail'd,X360,2010.0,Racing,Deep Silver,0.08,0.02,0.00,0.01,0.10
9852,9854,nail'd,PS3,2010.0,Racing,Deep Silver,0.08,0.02,0.00,0.02,0.12
10718,10720,iCarly 2: iJoin The Click!,Wii,2010.0,Adventure,Activision,0.08,0.01,0.00,0.01,0.10
11095,11097,Zoids Assault,X360,2007.0,Strategy,Takara Tomy,0.08,0.00,0.00,0.01,0.09
8495,8497,Zapper: One Wicked Cricket!,PS2,2002.0,Platform,Infogrames,0.08,0.06,0.00,0.02,0.16
10132,10134,Yu Yu Hakusho: Tournament Tactics,GBA,2004.0,Strategy,Atari,0.08,0.03,0.00,0.00,0.11
10173,10175,XXX,GBA,2002.0,Action,Activision,0.08,0.03,0.00,0.00,0.11
10569,10571,X-Men: The Official Game,XB,2006.0,Action,Activision,0.08,0.02,0.00,0.00,0.10

## 6. For the top-selling game of all time, how many standard deviations above/below the mean are its sales for North America?

In [23]:
NA_sale = df[["Name","NA_Sales","Global_Sales"]].sort_values("Global_Sales", ascending = False)[:1].iloc[0,1]
na_median_sales = int((NA_sale - df['NA_Sales'].mean())/df["NA_Sales"].std())
na_median_sales

50

## 7. The Nintendo Wii seems to have outdone itself with games. How does its average number of sales compare with all of the other platforms?

In [25]:
platform_comp = df[["Platform","Global_Sales"]].groupby("Platform").mean().sort_values("Global_Sales", ascending = False)
platform_comp

          Global_Sales
Platform
GB            2.606633
NES           2.561939
GEN           1.050370
SNES          0.837029
PS4           0.827679
X360          0.774672
2600          0.729925
PS3           0.720722
Wii           0.699404
N64           0.686144
XOne          0.662254
PS            0.610920
PS2           0.581046
WiiU          0.572448
3DS           0.486169
GBA           0.387470
DS            0.380254
GC            0.358561
XB            0.313422
SCD           0.311667
DC            0.307115
PC            0.269604
PSP           0.244254
WS            0.236667
SAT           0.194162
PSV           0.149952
NG            0.120000
TG16          0.080000
GG            0.040000
3DO           0.033333
PCFX          0.030000

In [31]:
def test():

    def assert_equal(actual,expected):
        assert actual == expected, f"Expected {expected} but got {actual}"

    assert_equal(most_common_publisher, "Electronic Arts")
    assert_equal(most_common_platform, "DS")
    assert_equal(most_common_genre, "Action")
    assert_equal(top_twenty_highest_grossing_games.iloc[0].Name, "Wii Sports")
    assert_equal(top_twenty_highest_grossing_games.iloc[19].Name, "Brain Age: Train Your Brain in Minutes a Day")
    assert_equal(na_median_sales, 50)

    print("Success!!!")

test()

Success!!!

## 8. The Nintendo GB seems to have the highest average sales among all the platforms. How does its total sales number compare with all of the other platforms?

In [106]:
df[["Platform","Global_Sales"]].groupby("Platform").sum().sort_values("Global_Sales", ascending = False)

          Global_Sales
Platform
PS2            1255.64
X360            979.96
PS3             957.84
Wii             926.71
DS              822.49
PS              730.66
GBA             318.50
PSP             296.28
PS4             278.10
PC              258.82
XB              258.26
GB              255.45
NES             251.07
3DS             247.46
N64             218.88
SNES            200.05
GC              199.36
XOne            141.06
2600             97.08
WiiU             81.86
PSV              61.93
SAT              33.59
GEN              28.36
DC               15.97
SCD               1.87
NG                1.44
WS                1.42
TG16              0.16
3DO               0.10
GG                0.04
PCFX              0.03

## 9. What are the global sales data for newer platforms after the year 2016?

In [115]:
df[df["Year"]>=2016][["Platform","Global_Sales"]].groupby("Platform").sum().sort_values("Global_Sales", ascending = False)

          Global_Sales
Platform
PS4              39.28
XOne             12.37
3DS               6.60
PSV               3.42
WiiU              3.29
PC                2.60
PS3               2.59
X360              0.83
DS                0.29